### ISSUE TITLE
Fork or merge my version of dbstress

### ISSUE THREAD

**Issue by PavanDendi** [semberal/dbstress#61]
Hi, first of all, thank you for this lovely bit of software!

I made some very quick and dirty changes in order to suit my needs and to be able to run this on Databricks.

Some of the major changes:
revert to scala 2.12
enable token based connection
dependency changes
force java 1.8

My question is...would you like me to clean up the code and send in a pull request?  Or would you prefer I fork?

Thank you!

ps.  You can find my changes here: https://github.com/PavanDendi/dbstress/commit/713fd9557c913c158ad5fb4aff75a3a16c3a9cd8

Don't say I didn't warn you about "quick and dirty" ;)

**Comment by semberal** [comment]
Hi, I am happy you find it useful :) I would like to go in a different direction and migrate to Scala 3 rather than reverting back to 2.12. Databricks requires Scala 2.12?

**Comment by PavanDendi** [comment]
Yes, unfortunately Databricks clusters are only available using 2.12.  What is the motivation behind moving to Scala 3 for dbstress?  Are the changes drastic enough that having multiple scala targets would be a lot of work?

**Comment by semberal** [comment]
I don't want to get stuck with 2.12, it is quite an old version already and in the future libraries likely won't support it anymore. With Scala 3 all these binary incompatibilities should go away. I also don't have the capacity and resources to test all changes with databricks. Moreover, some of the other changes you made, like provided dependencies, would not work outside of databricks. In this case I think it is easier if you fork the project and use a custom build with your modifications.

**Comment by PavanDendi** [comment]
Cool, no worries!  Thank you again for creating dbstress!
