### ISSUE TITLE
Random read query or read from files

### ISSUE THREAD

**Issue by lalu121212** [semberal/dbstress#62]
Hello,
Can we have random queries in config unit something similar as:
query: select name from employee where id=1;
<every run it will use some random id to fetch name)

Or can we have the query read from a os file where we can have all our expected database queries?

Thanks.

**Comment by semberal** [comment]
Hi,

as a workaround for now, could you generate the random numbers directly in the database? Something like this [should work](https://stackoverflow.com/questions/1400505/generate-a-random-number-in-the-range-1-10) with postgres:

```sql
select name from employee where id=(select (random()*9+1)::int);
```

**Comment by lalu121212** [comment]
Hi,
Yes we can use similar query to above in mysql. ( rand()  )
But those kind of queries did not use indexes even though there is index on id field.

Thanks.

**Comment by semberal** [comment]
I see, so I would propose to add the `query_params` to the unit configuration, which would look like this:

```yaml
query: select * from a where b = ? and c = ?
query_params: 
- value: 1
  type: long
- value: "abc"
  type: string
```

Each unit run would continuously loop over the parameters and execute the query. Would something like this work for you?

**Comment by lalu121212** [comment]
Hi Semberal,
Yes something like select * from a where b = ? and c = ? works .(Bind variable/prepared statement)
I feel it will be good if "b" and "c" from above example can read those inputs from some text files which holds some exact test case values. (Ex: some flatfile or a table holding employe_id,employee_name to be queried in actual query)
Thanks.

**Comment by semberal** [comment]
I would like to avoid having another external file. If you need to keep it in a separate text file, you can use some placeholder in the scenario config and replace it with the file content before running the test.

**Comment by lalu121212** [comment]
Hi,
While working on testing the script on MongoDB, came across some issues.
Config yaml is a s below:
unit_name: unit1
description: Example of a successful unit # optional
query: db.test.count()
uri: "jdbc:mongo://127.0.0.1:27017/admin"
username: testuser1
password: "xxxx" # optional if provided on command line
parallel_connections: 1
repeats: 1
connection_timeout: 3000 # in ms, optional

Its making connections to database but query part is failing:
When query: db.test.count(), below is the error-
12:49:23.108 [INFO] All database connections initialized, proceeding to the query execution phase
unity.parser.ParseException: Encountered " "(" "( "" at line 1, column 14.
Was expecting:
    ";" ...

	at unity.parser.uql.generateParseException(uql.java:5392)

And when query: select count(*) from test.test, it errors as below-
16:18:53.496 [INFO] All database connections initialized, proceeding to the query execution phase
16:18:53.807 [WARN] Query execution failed: Non-existing table referenced: test.test
16:18:53.821 [INFO] Finished unit runs: 1/1
16:18:53.823 [INFO] All database operations finished (1/1 calls failed)

So what will be query format when we test with other databases like mongo, cassandra etc?

Thanks.

**Comment by lalu121212** [comment]
Hi,

I was testing for few more databases, found it to be working with RDBMS system.
Still struggling with Nosql database ex: Mongodb.

Does it work with Nosql databases? if yes any specific driver to be used?
Thanks.

**Comment by lalu121212** [comment]
.
